[2022-03-30 21:57:01,986] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: twitter_dag.twitter_aluraonline 2022-03-31T00:56:41.663452+00:00 [queued]>
[2022-03-30 21:57:01,996] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: twitter_dag.twitter_aluraonline 2022-03-31T00:56:41.663452+00:00 [queued]>
[2022-03-30 21:57:01,996] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2022-03-30 21:57:01,996] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2022-03-30 21:57:01,997] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2022-03-30 21:57:02,005] {taskinstance.py:901} INFO - Executing <Task(TwitterOperator): twitter_aluraonline> on 2022-03-31T00:56:41.663452+00:00
[2022-03-30 21:57:02,008] {standard_task_runner.py:54} INFO - Started process 1482 to run task
[2022-03-30 21:57:02,069] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'twitter_dag', 'twitter_aluraonline', '2022-03-31T00:56:41.663452+00:00', '--job_id', '18', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/twitter_dag.py', '--cfg_path', '/var/folders/wt/20pgcb1j11323p97x03bt_g00000gr/T/tmppgyqm5jb']
[2022-03-30 21:57:02,074] {standard_task_runner.py:78} INFO - Job 18: Subtask twitter_aluraonline
[2022-03-30 21:57:02,128] {logging_mixin.py:112} INFO - Running <TaskInstance: twitter_dag.twitter_aluraonline 2022-03-31T00:56:41.663452+00:00 [running]> on host 1.0.0.127.in-addr.arpa
[2022-03-30 21:57:02,309] {base_hook.py:89} INFO - Using connection to: id: twitter_default. Host: http://api.twitter.com, Port: None, Schema: None, Login: None, Password: None, extra: XXXXXXXX
[2022-03-30 21:57:02,314] {twitter_hook.py:36} INFO - URL: http://api.twitter.com/2/tweets/search/recent?query=AluraOnline&tweet.fields=author_id,conversation_id,created_at,id,in_reply_to_user_id,public_metrics,text&expansions=author_id&user.fields=id,name,username,created_at&start_time=2022-03-31T00:56:41.00Z&end_time=2022-03-31T00:56:41.00Z
[2022-03-30 21:57:02,381] {logging_mixin.py:112} WARNING - /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/urllib3/connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.twitter.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
[2022-03-30 21:57:02,524] {http_hook.py:150} ERROR - HTTP error: Unauthorized
[2022-03-30 21:57:02,524] {http_hook.py:151} ERROR - {
  "title": "Unauthorized",
  "type": "about:blank",
  "status": 401,
  "detail": "Unauthorized"
}
[2022-03-30 21:57:02,531] {taskinstance.py:1150} ERROR - 401:Unauthorized
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/hooks/http_hook.py", line 148, in check_response
    response.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.twitter.com/2/tweets/search/recent?query=AluraOnline&tweet.fields=author_id,conversation_id,created_at,id,in_reply_to_user_id,public_metrics,text&expansions=author_id&user.fields=id,name,username,created_at&start_time=2022-03-31T00:56:41.00Z&end_time=2022-03-31T00:56:41.00Z

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/rafa/Documents/datapipeline/airflow/plugins/operators/twitter_operator.py", line 49, in execute
    for pg in hook.run():
  File "/Users/rafa/Documents/datapipeline/airflow/plugins/hooks/twitter_hook.py", line 56, in run
    yield from self.paginate(url, session)
  File "/Users/rafa/Documents/datapipeline/airflow/plugins/hooks/twitter_hook.py", line 45, in paginate
    data = self.connect_to_endpoint(full_url, session)
  File "/Users/rafa/Documents/datapipeline/airflow/plugins/hooks/twitter_hook.py", line 37, in connect_to_endpoint
    return self.run_and_check(session, prep, {}).json()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/hooks/http_hook.py", line 181, in run_and_check
    self.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/hooks/http_hook.py", line 152, in check_response
    raise AirflowException(str(response.status_code) + ":" + response.reason)
airflow.exceptions.AirflowException: 401:Unauthorized
[2022-03-30 21:57:02,540] {taskinstance.py:1187} INFO - Marking task as FAILED. dag_id=twitter_dag, task_id=twitter_aluraonline, execution_date=20220331T005641, start_date=20220331T005701, end_date=20220331T005702
[2022-03-30 21:57:06,981] {local_task_job.py:102} INFO - Task exited with return code 1
